Add docs for MongoDB
mindsdb/mindsdb-docs pull request #140
Opened 2021-04-14 11:07 UTC by ZoranPandovski

Added docs for MongoDB integration using GUI and mongo clients

2021-04-14 14:59 UTC, StpMax requested changes

2021-04-14 14:59 UTC, StpMax commented on mindsdb-docs/docs/datasources/mongodb.md
> +Currently, the MongoDB integration works only with MongoDB Atlas the cloud-hosted MongoDB service. Connecting MindsDB to MongoDB Atlas can be done in two ways:
Any mongodb can be used as datasource. You sure we should use 'only with MongoDB Atlas' here?

2021-04-14 14:59 UTC, StpMax commented on mindsdb-docs/docs/datasources/mongodb.md
> +    3. Add find query to select documents from the collection
At this moment 'find' must be valid json. Probably need mention it here

2021-04-14 14:59 UTC, StpMax commented on mindsdb-docs/docs/datasources/mongodb.md
> +![MindsDB-MongoDB](/assets/databases/mongodb/mongo-mdb.png)
I can not agree with 'ai layer' and 'direct integration'. This will be in future, at this moment mongo is just datasource and api

2021-04-14 14:59 UTC, StpMax commented on mindsdb-docs/docs/datasources/mongodb.md
> +            "database": "mindsdb",
this line can be removed

2021-04-14 14:59 UTC, StpMax commented on mindsdb-docs/docs/datasources/mongodb.md
> +After starting the server, you can list the collections in mindsdb database to make sure integration has been successful.
That completely wrong. Mongodb for mindsdb is only datasource at this moment

2021-04-14 14:59 UTC, StpMax commented on mindsdb-docs/docs/datasources/mongodb.md
> +```
I think we need add here exemple of how connect to mindsdb mongodb-api:
```
mongo --host 127.0.0.1
```

2021-04-14 14:59 UTC, StpMax commented on mindsdb-docs/docs/model/mongodb.md
> +
No, mongodb is only datasource for mindsdb.

2021-04-15 10:13 UTC, ZoranPandovski commented on mindsdb-docs/docs/datasources/mongodb.md
> +Currently, the MongoDB integration works only with MongoDB Atlas the cloud-hosted MongoDB service. Connecting MindsDB to MongoDB Atlas can be done in two ways:
I will change it to MongoDB

2021-04-15 11:51 UTC, ZoranPandovski commented on mindsdb-docs/docs/datasources/mongodb.md
> +![MindsDB-MongoDB](/assets/databases/mongodb/mongo-mdb.png)
Done, we will include both images for current and future integration.

2021-04-15 12:27 UTC, merged